services:
    api: &api
        image: caju-beneficios-api:development
        command: ${COMPOSE_DEVELOPMENT_COMMAND:-}
        build:
            target: development
        environment:
            APP_DEBUG: 1
            APP_ENVIRONMENT: development
            PYDEVD_DISABLE_FILE_VALIDATION: true
        volumes:
            - ./:/app
        ports:
            - ${APP_HOST_PORT:-8000}:${APP_HOST_PORT:-8000}
            - 5678:5678

    runner:
        <<: *api
        command: /bin/ash
